## Emulator
// @functionshost = http://localhost:5001/whereismybussg/us-central1
# Deployed
@functionshost = https://us-central1-whereismybussg.cloudfunctions.net
// @busStopCode = 03059
// @busStopCode = 12345
@busStopCode = 14141

###############################################################################
#
#
GET {{functionshost}}/initBusStops

###############################################################################
#
#
GET {{functionshost}}/listBusStops

###############################################################################
#
#
GET {{functionshost}}/deleteBusStops

###############################################################################
#
#
GET {{functionshost}}/busStops
    ?loc=1.265588,103.822327
    &num=1
    &usestore=1

###############################################################################
#
#
GET {{functionshost}}/busStops
    ?loc=1.265588,103.822327
    &num=1
    &usestore=false

###############################################################################
#
#
GET {{functionshost}}/busStops
    ?loc=1.265588,103.822327
    &num=1

###############################################################################
#
#
GET {{functionshost}}/busServices
    ?BusStopCode={{busStopCode}}

###############################################################################
#
# filter functions
GET {{functionshost}}/busArrivalv2
    ?BusStopCode={{busStopCode}}

###############################################################################
#
# REST API from lta
#
@ltaserver = http://datamall2.mytransport.sg
@apikey = zR1/YT/QS9C3uXMBjWQvZg==

###############################################################################
#
#
GET {{ltaserver}}/ltaodataservice/BusStops?$skip=500
AccountKey: {{apikey}}
Accept: application/json

###############################################################################
#
#
GET {{ltaserver}}/ltaodataservice/BusArrivalv2?BusStopCode=14141&ServiceNo=143
AccountKey: {{apikey}}
Accept: application/json

###############################################################################
#
#
GET {{ltaserver}}/ltaodataservice/BusArrivalv2?BusStopCode=14141
AccountKey: {{apikey}}
Accept: application/json


###############################################################################
#
#
GET http://datamall2.mytransport.sg/ltaodataservice/BusStop?$skip=50
AccountKey: {{apikey}}
Accept: application/json
